server:
  port: '8085'

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/micro_yt
    password: Jack@123
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

welcome:
  message: welcome to dev profile

management:
  endpoints:
    web:
      exposure:
        include: "*"
